// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <model/include/example/model/types/order_processed.hpp>


namespace example::analytics_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<std::unique_ptr<functions::CountOrderProcessed>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ProcessStreamConfig&)> count_order_processed;
    std::function<std::unique_ptr<functions::OrderProcessedEndpointSource>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_source;
  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::CountOrderProcessed> count_order_processed;
    std::unique_ptr<functions::OrderProcessedEndpointSource> order_processed_endpoint_source;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit() {}
  virtual void customFunctionsInit() {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initFunctions(const config::Config& config);
  void initRuntime();
  void initStreams(const config::Config& config);
  void initDataSources(const config::Config& config);
  void stopRuntime() noexcept;
  void releaseRuntime() noexcept;

  using ConsumeOrderProcessedInput =
      servicelib::InputStream<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr,
                              ServiceGenerated>;


  struct ServiceStreams final {
    ConsumeOrderProcessedInput* consume_order_processed{};
    servicelib::StreamBase* count_order_processed{nullptr};

  };
  ServiceStreams streams_;


  struct ServiceBindings final {
  };
  ServiceBindings bindings_;







  using ConsumeOrderProcessedKafkaSourceEndpoint =
      servicelib::datasource::kafka::Endpoint<
          example::model::types::OrderProcessed, example::model::types::OrderProcessed, functions::OrderProcessedEndpointSource, std::exception_ptr>;
  struct ConsumeOrderProcessedKafkaConsumerOwner final {
    ConsumeOrderProcessedKafkaConsumerOwner(
        servicelib::IServiceEnvironment& environment, int endpoint_id)
        : client(environment, endpoint_id) {}

    servicelib::datasource::kafka::LibrdkafkaConsumerClient client;
  };





  struct ServiceEndpoints final {
    std::shared_ptr<ConsumeOrderProcessedKafkaSourceEndpoint> consume_order_processed;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::unique_ptr<ConsumeOrderProcessedKafkaConsumerOwner> consume_order_processed_consumer;
  };
  ServiceConnectors connectors_;

  std::shared_ptr<servicelib::http::Router> http_router_;
  std::unique_ptr<servicelib::http::Server> http_server_;

  boost::asio::any_io_executor executor_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
};

}  // namespace example::analytics_service::app