// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>


#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasource/kafka/librdkafka.hpp>
#include <servicelib/datasource/localsource/custom.hpp>
#include <servicelib/datasource/cron/libcron.hpp>
#include <servicelib/datasink/localsink/custom.hpp>

#include <analyticsservice/internal/functions/analytics/count_order_processed.hpp>
#include <analyticsservice/internal/functions/cron/analytics_schedule_source.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/advance_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/complete_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/cycleanalytics/continue_cycle_analytics.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_orders_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_payments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/analytics_shipments_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_input_source.hpp>
#include <analyticsservice/internal/functions/endpoint/cycle_analytics_result_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/high_value_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/joined_analytics_sink.hpp>
#include <analyticsservice/internal/functions/endpoint/order_processed_endpoint_source.hpp>
#include <analyticsservice/internal/functions/endpoint/standard_analytics_sink.hpp>
#include <analyticsservice/internal/functions/joinanalytics/join_order_payment_analytics.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_orders_for_join.hpp>
#include <analyticsservice/internal/functions/joinanalytics/key_payments_for_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_orders_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_payments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/key_shipments_for_multi_join.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/multi_join_analytics_events.hpp>
#include <analyticsservice/internal/functions/multijoinanalytics/route_analytics_result.hpp>
#include <analyticsservice/internal/types/analytics_event.hpp>
#include <analyticsservice/internal/types/analytics_key.hpp>
#include <analyticsservice/internal/types/analytics_result.hpp>
#include <model_cpp/include/example/model/types/automation_job.hpp>
#include <model_cpp/include/example/model/types/order_processed.hpp>


namespace example::analytics_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::AdvanceCycleAnalytics>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> advance_cycle_analytics;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::AnalyticsOrdersSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> analytics_orders_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::AnalyticsPaymentsSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> analytics_payments_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::AnalyticsScheduleSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CronEndpointConfig&)> analytics_schedule_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::AnalyticsShipmentsSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> analytics_shipments_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::CompleteCycleAnalytics>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::FilterStreamConfig&)> complete_cycle_analytics;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::ContinueCycleAnalytics>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::FilterStreamConfig&)> continue_cycle_analytics;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::CountOrderProcessed>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ProcessStreamConfig&)> count_order_processed;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::CycleAnalyticsInputSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> cycle_analytics_input_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::CycleAnalyticsResultSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> cycle_analytics_result_sink;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::HighValueAnalyticsSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> high_value_analytics_sink;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::JoinOrderPaymentAnalytics>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::JoinStreamConfig&)> join_order_payment_analytics;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::JoinedAnalyticsSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> joined_analytics_sink;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::KeyOrdersForJoin>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KeyByStreamConfig&)> key_orders_for_join;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::KeyOrdersForMultiJoin>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KeyByStreamConfig&)> key_orders_for_multi_join;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::KeyPaymentsForJoin>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KeyByStreamConfig&)> key_payments_for_join;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::KeyPaymentsForMultiJoin>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KeyByStreamConfig&)> key_payments_for_multi_join;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::KeyShipmentsForMultiJoin>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KeyByStreamConfig&)> key_shipments_for_multi_join;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::MultiJoinAnalyticsEvents>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MultiJoinStreamConfig&)> multi_join_analytics_events;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::OrderProcessedEndpointSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::RouteAnalyticsResult>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CaseStreamConfig&)> route_analytics_result;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::StandardAnalyticsSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::CustomEndpointConfig&)> standard_analytics_sink;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;

  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::AdvanceCycleAnalytics> advance_cycle_analytics;
    std::unique_ptr<functions::AnalyticsOrdersSource> analytics_orders_source;
    std::unique_ptr<functions::AnalyticsPaymentsSource> analytics_payments_source;
    std::unique_ptr<functions::AnalyticsScheduleSource> analytics_schedule_source;
    std::unique_ptr<functions::AnalyticsShipmentsSource> analytics_shipments_source;
    std::unique_ptr<functions::CompleteCycleAnalytics> complete_cycle_analytics;
    std::unique_ptr<functions::ContinueCycleAnalytics> continue_cycle_analytics;
    std::unique_ptr<functions::CountOrderProcessed> count_order_processed;
    std::unique_ptr<functions::CycleAnalyticsInputSource> cycle_analytics_input_source;
    std::unique_ptr<functions::CycleAnalyticsResultSink> cycle_analytics_result_sink;
    std::unique_ptr<functions::HighValueAnalyticsSink> high_value_analytics_sink;
    std::unique_ptr<functions::JoinOrderPaymentAnalytics> join_order_payment_analytics;
    std::unique_ptr<functions::JoinedAnalyticsSink> joined_analytics_sink;
    std::unique_ptr<functions::KeyOrdersForJoin> key_orders_for_join;
    std::unique_ptr<functions::KeyOrdersForMultiJoin> key_orders_for_multi_join;
    std::unique_ptr<functions::KeyPaymentsForJoin> key_payments_for_join;
    std::unique_ptr<functions::KeyPaymentsForMultiJoin> key_payments_for_multi_join;
    std::unique_ptr<functions::KeyShipmentsForMultiJoin> key_shipments_for_multi_join;
    std::unique_ptr<functions::MultiJoinAnalyticsEvents> multi_join_analytics_events;
    std::unique_ptr<functions::OrderProcessedEndpointSource> order_processed_endpoint_source;
    std::unique_ptr<functions::RouteAnalyticsResult> route_analytics_result;
    std::unique_ptr<functions::StandardAnalyticsSink> standard_analytics_sink;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config,
                          const servicelib::config::ServiceConfig& service_config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void stopRuntime() noexcept;
  void releaseRuntime() noexcept;

  using AnalyticsScheduleInput =
      servicelib::InputStream<std::string, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using ConsumeOrderProcessedInput =
      servicelib::InputStream<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsOrdersInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsPaymentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using AnalyticsShipmentsInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;
  using CycleAnalyticsInputInput =
      servicelib::InputStream<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr,
                              ServiceGenerated>;

  using CycleAnalyticsLinkCycle =
      servicelib::CycleLinkStream<example::analytics_service::types::AnalyticsEvent, ServiceGenerated>;

  struct ServiceStreams final {
    AnalyticsScheduleInput* analytics_schedule{};
    ConsumeOrderProcessedInput* consume_order_processed{};
    AnalyticsOrdersInput* analytics_orders{};
    AnalyticsPaymentsInput* analytics_payments{};
    AnalyticsShipmentsInput* analytics_shipments{};
    CycleAnalyticsInputInput* cycle_analytics_input{};
    CycleAnalyticsLinkCycle* cycle_analytics_link{};
    servicelib::StreamBase* count_order_processed{nullptr};

    servicelib::StreamBase* split_analytics_orders{nullptr};

    servicelib::StreamBase* split_analytics_payments{nullptr};

    servicelib::StreamBase* merge_cycle_analytics{nullptr};

    servicelib::StreamBase* advance_cycle_analytics{nullptr};

    servicelib::StreamBase* split_cycle_analytics{nullptr};

    servicelib::StreamBase* complete_cycle_analytics{nullptr};

    servicelib::StreamBase* continue_cycle_analytics{nullptr};

    servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsEvent, std::monostate, std::exception_ptr> write_cycle_analytics;

    servicelib::StreamBase* key_orders_for_join{nullptr};

    servicelib::StreamBase* key_payments_for_join{nullptr};

    servicelib::StreamBase* join_order_payment_analytics{nullptr};

    servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_joined_analytics;

    servicelib::StreamBase* key_orders_for_multi_join{nullptr};

    servicelib::StreamBase* key_payments_for_multi_join{nullptr};

    servicelib::StreamBase* key_shipments_for_multi_join{nullptr};

    servicelib::StreamBase* multi_join_analytics_events{nullptr};

    servicelib::StreamBase* route_analytics_result{nullptr};

    servicelib::StreamBase* high_value_analytics{nullptr};

    servicelib::StreamBase* standard_analytics{nullptr};

    servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_high_value_analytics;

    servicelib::SinkEndpointStreamRef<example::analytics_service::types::AnalyticsResult, std::monostate, std::exception_ptr> write_standard_analytics;

  };
  ServiceStreams streams_;

  struct WriteCycleAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsEvent&)>
        consume;
    struct Function final {
      WriteCycleAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsEvent& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteJoinedAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteJoinedAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteHighValueAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteHighValueAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct WriteStandardAnalyticsSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::analytics_service::types::AnalyticsResult&)>
        consume;
    struct Function final {
      WriteStandardAnalyticsSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::analytics_service::types::AnalyticsResult& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    WriteCycleAnalyticsSinkBinding write_cycle_analytics;
    WriteJoinedAnalyticsSinkBinding write_joined_analytics;
    WriteHighValueAnalyticsSinkBinding write_high_value_analytics;
    WriteStandardAnalyticsSinkBinding write_standard_analytics;
  };
  ServiceBindings bindings_;







  using ConsumeOrderProcessedKafkaSourceEndpoint =
      servicelib::datasource::kafka::Endpoint<
          example::model::types::OrderProcessed, example::model::types::OrderProcessed, functions::OrderProcessedEndpointSource, std::exception_ptr>;
  struct ConsumeOrderProcessedKafkaConsumerOwner final {
    ConsumeOrderProcessedKafkaConsumerOwner(
        servicelib::IServiceEnvironment& environment, int endpoint_id)
        : client(environment, endpoint_id) {}

    servicelib::datasource::kafka::LibrdkafkaConsumerClient client;
  };


  using AnalyticsOrdersCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsOrdersSource, std::exception_ptr>;
  using AnalyticsPaymentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsPaymentsSource, std::exception_ptr>;
  using AnalyticsShipmentsCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::AnalyticsShipmentsSource, std::exception_ptr>;
  using CycleAnalyticsInputCustomSourceEndpoint =
      servicelib::datasource::localsource::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsInputSource, std::exception_ptr>;

  using WriteCycleAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsEvent, std::monostate, functions::CycleAnalyticsResultSink, std::exception_ptr>;
  using WriteJoinedAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::JoinedAnalyticsSink, std::exception_ptr>;
  using WriteHighValueAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::HighValueAnalyticsSink, std::exception_ptr>;
  using WriteStandardAnalyticsCustomSinkEndpoint =
      servicelib::datasink::localsink::Endpoint<
          example::analytics_service::types::AnalyticsResult, std::monostate, functions::StandardAnalyticsSink, std::exception_ptr>;


  struct ServiceEndpoints final {
    std::shared_ptr<ConsumeOrderProcessedKafkaSourceEndpoint> consume_order_processed;
    std::shared_ptr<AnalyticsOrdersCustomSourceEndpoint> analytics_orders;
    std::shared_ptr<AnalyticsPaymentsCustomSourceEndpoint> analytics_payments;
    std::shared_ptr<AnalyticsShipmentsCustomSourceEndpoint> analytics_shipments;
    std::shared_ptr<CycleAnalyticsInputCustomSourceEndpoint> cycle_analytics_input;
    std::shared_ptr<servicelib::datasource::cron::Endpoint> analytics_schedule;
    std::shared_ptr<WriteCycleAnalyticsCustomSinkEndpoint> write_cycle_analytics;
    std::shared_ptr<WriteJoinedAnalyticsCustomSinkEndpoint> write_joined_analytics;
    std::shared_ptr<WriteHighValueAnalyticsCustomSinkEndpoint> write_high_value_analytics;
    std::shared_ptr<WriteStandardAnalyticsCustomSinkEndpoint> write_standard_analytics;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::unique_ptr<ConsumeOrderProcessedKafkaConsumerOwner> consume_order_processed_consumer;
    std::shared_ptr<
        servicelib::datasource::cron::LibcronDataSource> local_cron_cron_source;
  };
  ServiceConnectors connectors_;

  std::shared_ptr<servicelib::http::Router> http_router_;
  std::unique_ptr<servicelib::http::Server> http_server_;

  boost::asio::any_io_executor executor_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
};

}  // namespace example::analytics_service::app