// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/status/http.hpp>

namespace example::analytics_service::app {

ServiceGenerated::ServiceGenerated(
    boost::asio::any_io_executor executor,

    std::shared_ptr<const config::Config> config,
    servicelib::log::Logger& logger,
    servicelib::metrics::Metrics& metrics,
    servicelib::tracing::Tracing* tracing)
    : executor_(std::move(executor)),

      config_(std::move(config)),
      logger_(&logger),
      metrics_(&metrics),
      tracing_(tracing) {
  if (!executor_) {
    throw std::invalid_argument("service Asio executor is not initialized");
  }
  if (!config_) {
    throw std::invalid_argument("service config is null");
  }
  runtime_config_ =
      servicelib::config::detail::MakeRuntimeConfigSnapshot(config_);
}

ServiceGenerated::~ServiceGenerated() {
  stopRuntime();
  releaseRuntime();
}

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    servicelib::config::RuntimeConfigRegistry::Publish(runtime_config_);
    serviceInit();
    makers_.initMakers(executor_);
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    lifecycle_started_ = true;
    servers_.http_server_->Start();
    serviceStarted();
  } catch (...) {
    stop();
    throw;
  }
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  this->ensureConfiguredPools();
  const auto service_config = getServiceConfigSnapshot();
  if (!service_config) {
    throw std::runtime_error("service config is null");
  }
  servers_.initInfrastructure(*this, context, *config_snapshot, *service_config);
  functions_.initFunctions(context, *config_snapshot, *this, makers_, executor_);
  customFunctionsInit(context);
  streams_.initStreams(*config_snapshot, *this);
  streams_.build(*config_snapshot, *this, functions_, bindings_);
  substreams_.bind(streams_);
  endpoints_.initDataSinks(*this, *config_snapshot);

  endpoints_.initDataSources(*this, *config_snapshot);
  servicelib::http::RegisterStatusRoutes(
      *servers_.http_router_, *this, [this] {
        if (const auto* prometheus =
                dynamic_cast<const servicelib::metrics::PrometheusMetrics*>(
                    metrics_)) {
          return prometheus->Expose();
        }
        return std::string{};
      }, service_config->statusHandler, service_config->metricsHandler,
      service_config->startupHandler, service_config->readinessHandler,
      service_config->livenessHandler);
}

void ServiceGenerated::stop(servicelib::Context context) noexcept {
  try {
    auto lifetime = getShutdownLifetime();
    if (!lifetime) {
      // An externally owned service cannot safely outlive its caller.
      stopSynchronously(context);
      return;
    }
    if (const auto config = getServiceConfigSnapshot();
        config && config->shutdownTimeout > 0) {
      context = context.bounded(
          std::chrono::milliseconds{config->shutdownTimeout});
    }
    std::optional<servicelib::detail::ShutdownTask> task;
    {
      std::lock_guard lock(shutdown_mutex_);
      if (!shutdown_task_) {
        shutdown_task_.emplace([this, context, lifetime = std::move(lifetime)] {
          stopSynchronously(context);
          waitForShutdown();
        });
      }
      task = shutdown_task_;
    }
    if (task->wait(context)) {
      if (auto error = task->get()) std::rethrow_exception(error);
    }
  } catch (const std::exception& error) {
    try {
      getLogger().error("generated service shutdown failed",
                       {servicelib::log::Field::Err(error.what())});
    } catch (...) {
    }
  } catch (...) {
    try {
      getLogger().error("generated service shutdown failed");
    } catch (...) {
    }
  }
}

void ServiceGenerated::waitStopped() {
  std::optional<servicelib::detail::ShutdownTask> task;
  {
    std::lock_guard lock(shutdown_mutex_);
    task = shutdown_task_;
  }
  if (task) {
    if (auto error = task->get()) std::rethrow_exception(error);
  } else {
    waitForShutdown();
  }
}

void ServiceGenerated::stopSynchronously(servicelib::Context context) noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (lifecycle_started_) {
      lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  stopRuntime(context);
}

void ServiceGenerated::stopRuntime(servicelib::Context context) noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  if (servers_.http_server_) {
    servers_.http_server_->Stop();
    servers_.http_server_->WaitStopped();
  }
  clients_.stop();

  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop(context);
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  clients_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
  servers_.http_server_.reset();
  servers_.http_router_.reset();
  servicelib::config::RuntimeConfigRegistry::Publish({});
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return *logger_;
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return *metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return tracing_;
}


}  // namespace example::analytics_service::app