// Code generated by servicegen. DO NOT EDIT.
#include "analyticsservice/internal/app/service.generated.hpp"

#include <algorithm>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>
#include <chrono>
#include <cstdint>
#include <exception>
#include <future>
#include <mutex>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/status/http.hpp>

#include "analyticsservice/internal/app/service.hpp"

namespace example::analytics_service::app {

ServiceGenerated::ServiceGenerated(
    boost::asio::any_io_executor executor,

    std::shared_ptr<const config::Config> config,
    servicelib::log::Logger& logger,
    servicelib::metrics::Metrics& metrics,
    servicelib::tracing::Tracing* tracing)
    : executor_(std::move(executor)),

      config_(std::move(config)),
      logger_(&logger),
      metrics_(&metrics),
      tracing_(tracing) {
  if (!executor_) {
    throw std::invalid_argument("service Asio executor is not initialized");
  }
  if (!config_) {
    throw std::invalid_argument("service config is null");
  }
  runtime_config_ =
      servicelib::config::detail::MakeRuntimeConfigSnapshot(config_);
}

ServiceGenerated::~ServiceGenerated() {
  stopRuntime();
  releaseRuntime();
}

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    servicelib::config::RuntimeConfigRegistry::Publish(runtime_config_);
    serviceInit();
    initMakers();
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    lifecycle_started_ = true;
    http_server_->Start();
    serviceStarted();
  } catch (...) {
    stop();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.analytics_schedule_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::CronEndpointConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::AnalyticsScheduleSource>> {
    return functions::MakeAnalyticsScheduleSource(
        std::move(context), environment, config);
  };
  makers_.count_order_processed = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ProcessStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::CountOrderProcessed>> {
    return functions::MakeCountOrderProcessed(
        std::move(context), environment, config);
  };
  makers_.order_processed_endpoint_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KafkaEndpointConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::OrderProcessedEndpointSource>> {
    return functions::MakeOrderProcessedEndpointSource(
        std::move(context), environment, config);
  };
  makers_.http_router = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config)
      -> boost::asio::awaitable<std::shared_ptr<servicelib::http::Router>> {
    (void)context;
    (void)environment;
    (void)config;
    co_return std::make_shared<servicelib::http::Router>();
  };
  makers_.http_server = [this](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config,
      std::shared_ptr<servicelib::http::Router> router)
      -> boost::asio::awaitable<std::unique_ptr<servicelib::http::Server>> {
    (void)context;
    (void)environment;
    if (config.httpPort < 0 || config.httpPort > 65535) {
      throw std::invalid_argument("service HTTP port is out of range");
    }
    servicelib::http::Server::Options options;
    options.address = config.httpHost.empty() ? std::string{"0.0.0.0"}
                                               : config.httpHost;
    options.port = static_cast<std::uint16_t>(config.httpPort);
    options.shutdownTimeout =
        std::chrono::milliseconds{std::max(config.shutdownTimeout, 0)};
    co_return std::make_unique<servicelib::http::Server>(
        executor_, std::move(router), std::move(options));
  };
}

void ServiceGenerated::initInfrastructure(
    servicelib::Context context, const config::Config& cfg,
    const servicelib::config::ServiceConfig& service_config) {
  if (!makers_.http_router || !makers_.http_server) {
    throw std::logic_error("HTTP infrastructure makers are not configured");
  }
  http_router_ = boost::asio::co_spawn(
      executor_, makers_.http_router(context, *this, service_config),
      boost::asio::use_future).get();
  if (!http_router_) {
    throw std::logic_error("HTTP router maker returned null");
  }
  std::stop_source maker_cancellation;
  std::mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<std::future<void>> maker_tasks;
  const auto launch = [&](auto task) {
    maker_tasks.push_back(boost::asio::co_spawn(
        executor_, std::move(task), boost::asio::use_future));
  };
  launch([this, service_config, maker_context, &maker_cancellation,
          &maker_error_mutex, &first_maker_error]()
             -> boost::asio::awaitable<void> {
    try {
      http_server_ = co_await makers_.http_server(
          maker_context, *this, service_config, http_router_);
      if (!http_server_) throw std::logic_error("HTTP server maker returned null");
    } catch (...) {
      maker_cancellation.request_stop();
      const std::lock_guard lock(maker_error_mutex);
      if (!first_maker_error) first_maker_error = std::current_exception();
      throw;
    }
  }());
  for (auto& task : maker_tasks) {
    try {
      task.get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initFunctions(
    servicelib::Context context, const config::Config& cfg) {
  if (!makers_.analytics_schedule_source) {
    throw std::logic_error("function maker AnalyticsScheduleSource is not configured");
  }
  if (!makers_.count_order_processed) {
    throw std::logic_error("function maker CountOrderProcessed is not configured");
  }
  if (!makers_.order_processed_endpoint_source) {
    throw std::logic_error("function maker OrderProcessedEndpointSource is not configured");
  }
  std::stop_source maker_cancellation;
  std::mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<std::future<void>> maker_tasks;
  maker_tasks.reserve(3);
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [this, &cfg, maker_context, &maker_cancellation, &maker_error_mutex,
       &first_maker_error]() -> boost::asio::awaitable<void> {
    try {
      functions_.analytics_schedule_source = co_await makers_.analytics_schedule_source(
          maker_context, *this, cfg.endpoints.analyticsSchedule);
      if (!functions_.analytics_schedule_source) {
        throw std::logic_error("function maker AnalyticsScheduleSource returned null");
      }
    } catch (...) {
      maker_cancellation.request_stop();
      const std::lock_guard lock(maker_error_mutex);
      if (!first_maker_error) {
        first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [this, &cfg, maker_context, &maker_cancellation, &maker_error_mutex,
       &first_maker_error]() -> boost::asio::awaitable<void> {
    try {
      functions_.count_order_processed = co_await makers_.count_order_processed(
          maker_context, *this, cfg.streams.countOrderProcessed);
      if (!functions_.count_order_processed) {
        throw std::logic_error("function maker CountOrderProcessed returned null");
      }
    } catch (...) {
      maker_cancellation.request_stop();
      const std::lock_guard lock(maker_error_mutex);
      if (!first_maker_error) {
        first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [this, &cfg, maker_context, &maker_cancellation, &maker_error_mutex,
       &first_maker_error]() -> boost::asio::awaitable<void> {
    try {
      functions_.order_processed_endpoint_source = co_await makers_.order_processed_endpoint_source(
          maker_context, *this, cfg.endpoints.orderProcessed);
      if (!functions_.order_processed_endpoint_source) {
        throw std::logic_error("function maker OrderProcessedEndpointSource returned null");
      }
    } catch (...) {
      maker_cancellation.request_stop();
      const std::lock_guard lock(maker_error_mutex);
      if (!first_maker_error) {
        first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(), boost::asio::use_future));

  for (auto& task : maker_tasks) {
    try {
      task.get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  this->ensureConfiguredPools();
  const auto service_config = getServiceConfigSnapshot();
  if (!service_config) {
    throw std::runtime_error("service config is null");
  }
  initInfrastructure(context, *config_snapshot, *service_config);
  initFunctions(context, *config_snapshot);
  customFunctionsInit(context);
  initStreams(*config_snapshot);

  initDataSources(*config_snapshot);
  servicelib::http::RegisterStatusRoutes(
      *http_router_, *this, [this] {
        if (const auto* prometheus =
                dynamic_cast<const servicelib::metrics::PrometheusMetrics*>(
                    metrics_)) {
          return prometheus->Expose();
        }
        return std::string{};
      }, service_config->statusHandler, service_config->metricsHandler,
      service_config->startupHandler, service_config->readinessHandler,
      service_config->livenessHandler);
}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.analytics_schedule = &servicelib::makeInputStreamRef<std::string, std::monostate, std::exception_ptr, ServiceGenerated>(cfg.streams.analyticsSchedule, nullptr, *this);
  streams_.consume_order_processed = &servicelib::makeInputStreamRef<example::model::types::OrderProcessed, example::model::types::OrderProcessed, std::exception_ptr, ServiceGenerated>(cfg.streams.consumeOrderProcessed, nullptr, *this);
  auto& count_order_processed = (*streams_.consume_order_processed).process(cfg.streams.countOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(std::ref(*functions_.count_order_processed)));
  streams_.count_order_processed = std::addressof(count_order_processed);
  streams_.consume_order_processed->setSource(count_order_processed);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;


  connectors_.consume_order_processed_consumer =
      std::make_unique<ConsumeOrderProcessedKafkaConsumerOwner>(
          *this, cfg.endpoints.orderProcessed.id);
  endpoints_.consume_order_processed = ConsumeOrderProcessedKafkaSourceEndpoint::make(
      *this, *streams_.consume_order_processed, connectors_.consume_order_processed_consumer->client,
      *functions_.order_processed_endpoint_source);
  registerDataSource(endpoints_.consume_order_processed);

  connectors_.local_cron_cron_source =
      servicelib::datasource::cron::LibcronDataSource::make(
          *this, cfg.dataConnectors.localCron.id);
  endpoints_.analytics_schedule =
      servicelib::datasource::cron::Endpoint::make(
          *this, *streams_.analytics_schedule, *functions_.analytics_schedule_source);
  connectors_.local_cron_cron_source->addEndpoint(endpoints_.analytics_schedule);
  registerDataSource(connectors_.local_cron_cron_source);

}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (lifecycle_started_) {
      lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  stopRuntime();
}

void ServiceGenerated::stopRuntime() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  if (http_server_) http_server_->Stop();


  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
  http_server_.reset();
  http_router_.reset();
  servicelib::config::RuntimeConfigRegistry::Publish({});
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return *logger_;
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return *metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return tracing_;
}

}  // namespace example::analytics_service::app