// Code generated by servicegen. DO NOT EDIT.
#include <csignal>
#include <chrono>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <memory>
#include <future>
#include <stdexcept>
#include <string>


#include <servicelib/runtime/detail/asio_runtime.hpp>

#include <servicelib/runtime/config/command_line.hpp>
#include <servicelib/runtime/config/loader.hpp>
#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/environment_variable.hpp>
#include <servicelib/runtime/logging/logging.hpp>
#include <servicelib/runtime/telemetry/opentelemetry/opentelemetry.hpp>

#include "analyticsservice/config/config.generated.hpp"
#include "analyticsservice/internal/app/service.hpp"


int main(int argc, char* argv[]) {
  try {

    const auto options = servicelib::config::CommandLine::Parse(argc, argv);
    using Config = example::analytics_service::config::Config;
    const bool noop_logs =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_LOGS");
    const bool noop_metrics =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_METRICS");
    const bool noop_tracing =
        servicelib::EnvironmentFlagEnabled("SERVICELIB_NOOP_TRACING");
    servicelib::log::Logger& bootstrap_logger =
        noop_logs
            ? servicelib::log::NoopLogger::instance()
            : servicelib::logging::createLogsEngine(
                  servicelib::logging::LogsEngineType::kBoost);
    std::unique_ptr<servicelib::metrics::PrometheusMetrics> prometheus_metrics;
    servicelib::metrics::Metrics* metrics =
        &servicelib::metrics::NoopMetrics::instance();
    if (!noop_metrics) {
      prometheus_metrics =
          std::make_unique<servicelib::metrics::PrometheusMetrics>();
      metrics = prometheus_metrics.get();
    }
    servicelib::config::ConfigLoader<Config> loader(
        {.configPath = options.configPath,
         .overridePath = options.valuesPath},
        {}, bootstrap_logger, *metrics, "");
    const auto runtime_config = loader.Load();
    const auto config = loader.GetConfig();
    const auto& own_service_config =
        config->services.analyticsService;
    namespace otel = servicelib::telemetry::opentelemetry_adapter;
    std::unique_ptr<otel::OpenTelemetryLogger> otlp_logs;
    std::unique_ptr<otel::OpenTelemetryTracing> tracing;
    servicelib::log::Logger* service_logger = &bootstrap_logger;
    switch (own_service_config.environment) {
      case servicelib::api::Environment::kStaging:
      case servicelib::api::Environment::kProduction:
        if (!noop_logs) {
          otlp_logs = otel::CreateOTLPLogsEngine(own_service_config.name);
          service_logger = otlp_logs.get();
        }
        if (!noop_tracing) {
          tracing =
              otel::CreateOTLPTracingEngine(own_service_config.name);
        }
        break;
      default:
        if (!noop_tracing) {
          tracing =
              otel::CreateStdoutTracingEngine(own_service_config.name);
        }
        break;
    }
    servicelib::async::Runtime runtime(
        {.workers = options.workers,
         .unhandledException = {},
         .metrics = metrics});

    example::analytics_service::app::Service service(runtime.executor(),
                                    config, *service_logger,
                                    *metrics, tracing.get());
    bool runtime_shutdown{};
    const auto shutdown_runtime = [&] {
      if (runtime_shutdown) return;
      loader.Stop();
      service.stop();
      runtime.stop();
      runtime.join();
      runtime_shutdown = true;
    };
    try {
      runtime.start();
      service.start();
      loader.Start(std::chrono::seconds{5},
                   [](std::shared_ptr<const servicelib::config::RuntimeConfig>
                          next_config) {
                     servicelib::config::RuntimeConfigRegistry::Publish(
                         std::move(next_config));
                   });

      std::promise<void> shutdown;
      auto shutdown_requested = shutdown.get_future();
      runtime.waitForSignals({SIGINT, SIGTERM},
                             [&](int) { shutdown.set_value(); });
      shutdown_requested.wait();
      shutdown_runtime();
      const bool tracing_flushed = !tracing || tracing->forceFlush();
      const bool tracing_stopped = !tracing || tracing->shutdown();
      const bool logs_flushed = !otlp_logs || otlp_logs->forceFlush();
      const bool logs_stopped = !otlp_logs || otlp_logs->shutdown();
      if (!tracing_flushed || !tracing_stopped || !logs_flushed ||
          !logs_stopped) {
        throw std::runtime_error("failed to flush OpenTelemetry providers");
      }
    } catch (...) {
      try {
        shutdown_runtime();
      } catch (...) {
        // Preserve the original startup/runtime failure.
      }
      throw;
    }
    return 0;
  } catch (const std::exception& error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}