// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/service.generated.hpp"

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <exception>
#include <stdexcept>
#include <string>
#include <string_view>

#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/status/http.hpp>

#include "inventoryservice/internal/app/service.hpp"

namespace example::inventory_service::app {

ServiceGenerated::ServiceGenerated(
    boost::asio::any_io_executor executor,
    agrpc::GrpcContext& grpc_context,

    std::shared_ptr<const config::Config> config,
    servicelib::log::Logger& logger,
    servicelib::metrics::Metrics& metrics,
    servicelib::tracing::Tracing* tracing)
    : executor_(std::move(executor)),
      grpc_context_(&grpc_context),

      config_(std::move(config)),
      logger_(&logger),
      metrics_(&metrics),
      tracing_(tracing) {
  if (!executor_) {
    throw std::invalid_argument("service Asio executor is not initialized");
  }
  if (!config_) {
    throw std::invalid_argument("service config is null");
  }
  runtime_config_ =
      servicelib::config::detail::MakeRuntimeConfigSnapshot(config_);
}

ServiceGenerated::~ServiceGenerated() {
  stopRuntime();
  releaseRuntime();
}

void ServiceGenerated::start() {
  try {
    servicelib::config::RuntimeConfigRegistry::Publish(runtime_config_);
    serviceInit();
    initMakers();
    customMakersInit();
    initRuntime();
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    lifecycle_started_ = true;
    http_server_->Start();
    serviceStarted();
  } catch (...) {
    stop();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.get_inventory_item_data = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ProcessStreamConfig& config) {
    return functions::MakeGetInventoryItemData(
        std::move(context), environment, config);
  };
  makers_.process_order_item = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcEndpointConfig& config) {
    return functions::MakeProcessOrderItem(
        std::move(context), environment, config);
  };
}

void ServiceGenerated::initFunctions(const config::Config& cfg) {
  if (!makers_.get_inventory_item_data) {
    throw std::logic_error("function maker GetInventoryItemData is not configured");
  }
  functions_.get_inventory_item_data = makers_.get_inventory_item_data(
      servicelib::Context{}, *this, cfg.streams.getInventoryItemData);
  if (!functions_.get_inventory_item_data) {
    throw std::logic_error("function maker GetInventoryItemData returned null");
  }
  if (!makers_.process_order_item) {
    throw std::logic_error("function maker ProcessOrderItem is not configured");
  }
  functions_.process_order_item = makers_.process_order_item(
      servicelib::Context{}, *this, cfg.endpoints.processOrderItem);
  if (!functions_.process_order_item) {
    throw std::logic_error("function maker ProcessOrderItem returned null");
  }
}

void ServiceGenerated::initRuntime() {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  this->ensureConfiguredPools();
  initFunctions(*config_snapshot);
  customFunctionsInit();
  initStreams(*config_snapshot);
  http_router_ = std::make_shared<servicelib::http::Router>();
  const auto service_config = getServiceConfigSnapshot();
  if (!service_config) {
    throw std::runtime_error("service config is null");
  }
  if (service_config->httpPort < 0 || service_config->httpPort > 65535) {
    throw std::invalid_argument("service HTTP port is out of range");
  }
  servicelib::http::Server::Options http_options;
  http_options.address = service_config->httpHost.empty()
                             ? std::string{"0.0.0.0"}
                             : service_config->httpHost;
  http_options.port = static_cast<std::uint16_t>(service_config->httpPort);
  http_options.shutdownTimeout = std::chrono::milliseconds{
      std::max(service_config->shutdownTimeout, 0)};
  http_server_ = std::make_unique<servicelib::http::Server>(
      executor_, http_router_, std::move(http_options));
  initDataSources(*config_snapshot);
  servicelib::http::RegisterStatusRoutes(
      *http_router_, *this, [this] {
        if (const auto* prometheus =
                dynamic_cast<const servicelib::metrics::PrometheusMetrics*>(
                    metrics_)) {
          return prometheus->Expose();
        }
        return std::string{};
      }, service_config->statusHandler, service_config->metricsHandler,
      service_config->startupHandler, service_config->readinessHandler,
      service_config->livenessHandler);
}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.process_inventory_item = &servicelib::makeInputStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, *this);
  auto& get_inventory_item_data = (*streams_.process_inventory_item).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_data)));
  streams_.get_inventory_item_data = std::addressof(get_inventory_item_data);
  auto& merge_inventory_result = get_inventory_item_data.merge(cfg.streams.mergeInventoryResult, get_inventory_item_data.getErrorStream());
  streams_.merge_inventory_result = std::addressof(merge_inventory_result);
  streams_.process_inventory_item->setSource(merge_inventory_result);
}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;
  connectors_.inventory_service_api_source =
      servicelib::datasource::grpc::DataSource::make(
          *this, *streams_.process_inventory_item);
  endpoints_.process_inventory_item = ProcessInventoryItemGrpcSourceConsumer::make(
      *this, *streams_.process_inventory_item,
      *functions_.process_order_item);
  connectors_.inventory_service_api_source->addEndpoint(endpoints_.process_inventory_item->endpoint());
  registerDataSource(connectors_.inventory_service_api_source);




}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (lifecycle_started_) {
      lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  stopRuntime();
}

void ServiceGenerated::stopRuntime() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  if (http_server_) http_server_->Stop();


  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
  http_server_.reset();
  http_router_.reset();
  servicelib::config::RuntimeConfigRegistry::Publish({});
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return *logger_;
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return *metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return tracing_;
}

}  // namespace example::inventory_service::app