// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "inventoryservice/config/config.generated.hpp"
#include "inventoryservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasource/grpc/asio.hpp>
#include <servicelib/datasource/http/beast.hpp>

#include <inventoryservice/internal/functions/endpoint/process_order_item_source.hpp>
#include <inventoryservice/internal/functions/inventory_item/get_inventory_item_data.hpp>
#include <model_cpp/include/example/model/types/order_item.hpp>
#include <model_cpp/include/example/model/types/order_item_result.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::inventory_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,
                   agrpc::GrpcContext& grpc_context,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::GetInventoryItemData>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ProcessStreamConfig&)> get_inventory_item_data;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::ProcessOrderItemSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcEndpointConfig&)> process_order_item_source;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;
  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::GetInventoryItemData> get_inventory_item_data;
    std::unique_ptr<functions::ProcessOrderItemSource> process_order_item_source;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config,
                          const servicelib::config::ServiceConfig& service_config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSources(const config::Config& config);
  void stopRuntime() noexcept;
  void releaseRuntime() noexcept;

  using ProcessInventoryItemInput =
      servicelib::InputStream<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr,
                              ServiceGenerated>;


  struct ServiceStreams final {
    ProcessInventoryItemInput* process_inventory_item{};
    servicelib::StreamBase* get_inventory_item_data{nullptr};

    servicelib::StreamBase* merge_inventory_result{nullptr};

  };
  ServiceStreams streams_;


  struct ServiceBindings final {
  };
  ServiceBindings bindings_;

  using ProcessInventoryItemGrpcSourceEndpoint =
      servicelib::datasource::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSource, std::exception_ptr>;
  using ProcessInventoryItemGrpcSourceConsumer =
      servicelib::datasource::grpc::EndpointConsumer<
          ProcessInventoryItemInput, ProcessInventoryItemGrpcSourceEndpoint, functions::ProcessOrderItemSource>;

 public:
  std::shared_ptr<ProcessInventoryItemGrpcSourceEndpoint> grpcSourceEndpointProcessInventoryItem() const noexcept {
    return endpoints_.process_inventory_item ? endpoints_.process_inventory_item->endpoint() : nullptr;
  }

 private:










  struct ServiceEndpoints final {
    std::shared_ptr<ProcessInventoryItemGrpcSourceConsumer> process_inventory_item;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::shared_ptr<
        servicelib::datasource::grpc::DataSource> inventory_service_api_source;
  };
  ServiceConnectors connectors_;

  std::shared_ptr<servicelib::http::Router> http_router_;
  std::unique_ptr<servicelib::http::Server> http_server_;

  boost::asio::any_io_executor executor_;
  agrpc::GrpcContext* grpc_context_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
};

}  // namespace example::inventory_service::app