// Code generated by servicegen. DO NOT EDIT.
#include "inventoryservice/internal/app/service.generated.hpp"
#include <algorithm>
#include <chrono>
#include <mutex>
#include <stop_token>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>

namespace example::inventory_service::app {



void ServiceStreams::initStreams(const config::Config& cfg, ServiceGenerated& service) {
  auto& streams_ = *this;
  (void)cfg; (void)service; (void)streams_;
  streams_.process_inventory_item = &servicelib::makeInputStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, std::exception_ptr, ServiceGenerated>(cfg.streams.processInventoryItem, nullptr, service);

}

void ServiceStreams::build(const config::Config& cfg, ServiceGenerated& service, ServiceFunctions& functions_, ServiceBindings& bindings_) {
  auto& streams_ = *this;
  (void)cfg; (void)service; (void)functions_; (void)bindings_; (void)streams_;
  auto& get_inventory_item_data = (*streams_.process_inventory_item).process(cfg.streams.getInventoryItemData, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::inventory_service::types::InventoryFailure>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_data)));
  streams_.get_inventory_item_data = std::addressof(get_inventory_item_data);
  auto& map_inventory_item_error = get_inventory_item_data.getErrorStream().map(cfg.streams.mapInventoryItemError, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamFunction(std::ref(*functions_.get_inventory_item_error)));
  streams_.map_inventory_item_error = std::addressof(map_inventory_item_error);
  auto& merge_inventory_result = get_inventory_item_data.merge(cfg.streams.mergeInventoryResult, map_inventory_item_error);
  streams_.merge_inventory_result = std::addressof(merge_inventory_result);
  streams_.process_inventory_item->setSource(merge_inventory_result);

}

}  // namespace example::inventory_service::app