services:
  analyticsservice:
    image: cppboostexample-analyticsservice
    working_dir: /app
    command:
      - --config
      - /app/config/config.yaml
      - --values
      - /app/config/overrides.integration.generated.yaml
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
    ports:
      - "9093:9093"
      - "9203:9203"
      - "2345:2345"