# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

export SERVICEGEN_FETCH_CPP_DEPENDENCIES := OFF

ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST ?= host.docker.internal
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= $(SERVICEGEN_NEXUS_PORT)
SERVICEGEN_DEPENDENCY_PROXY_PORT := $(if $(SERVICEGEN_DEPENDENCY_PROXY_PORT),$(SERVICEGEN_DEPENDENCY_PROXY_PORT),18081)
export SERVICEGEN_CONAN_HOME := $(SERVICEGEN_DEPENDENCY_PROXY_DIR)/conan2
export SERVICEGEN_GITHUB_RAW_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw
export SERVICEGEN_CONAN_REMOTE_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/conan-proxy
export CPPBOOSTSERVICELIB_SOURCE_CONTEXT ?= http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw/gorundebug/cppboostservicelib/archive/refs/tags/v0.2.17.tar.gz
export SERVICELIB_SOURCE_CONTEXT ?= $(CPPBOOSTSERVICELIB_SOURCE_CONTEXT)
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export SERVICEGEN_GITHUB_RAW_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export SERVICEGEN_CONAN_REMOTE_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/conan-proxy
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export PIP_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST)
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export SERVICEGEN_APT_UBUNTU_ARCHIVE_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/apt-ubuntu-archive
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export SERVICEGEN_APT_UBUNTU_SECURITY_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/apt-ubuntu-security
build test release-build release-test asan-test tsan-test lint docker-build docker-up: export SERVICEGEN_APT_UBUNTU_PORTS_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/apt-ubuntu-ports
endif

.PHONY: build test release-build release-test asan-test tsan-test release-up lint fmt clean \
	docker-build docker-up docker-down docker-clean help

build: ## Build the standalone service in the canonical Docker toolchain
	@./scripts/build.generated.sh docker-debug

test: ## Build and run all service tests
	@./scripts/test.generated.sh docker-debug

release-build: ## Build the optimized standalone service in Docker
	@./scripts/build.generated.sh docker-release

release-test: ## Build and test the optimized standalone service
	@./scripts/test.generated.sh docker-release

asan-test: ## Run standalone service tests with ASan and UBSan
	@SERVICEGEN_SANITIZER_INTEGRATION=0 ./scripts/sanitizer-test.generated.sh asan

tsan-test: ## Run standalone service tests with TSan
	@SERVICEGEN_SANITIZER_INTEGRATION=0 ./scripts/sanitizer-test.generated.sh tsan

release-up: release-build ## Build the optimized service

lint: ## Run generated clang-format and clang-tidy targets
	@./scripts/lint.generated.sh

fmt: ## Format C++ sources
	@find . -type f \( -name '*.cpp' -o -name '*.hpp' \) -not -path './build/*' \
		-exec clang-format -i {} +

clean: ## Remove CMake build artifacts
	@docker compose -f docker-compose.cmake.generated.yml down --volumes --remove-orphans
	@rm -rf build

docker-build: build ## Build the reusable C++ toolchain image and service
	@docker compose -f docker-compose.cmake.generated.yml build cpp-build

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose up -d

docker-down: ## Stop this service
	@docker compose down

docker-clean: docker-down clean ## Stop the service and remove all volumes
	@docker compose down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'