services:
  orderservice:
    image: cppboostexample-orderservice
    working_dir: /app
    command:
      - --config
      - /app/config/config.yaml
      - --values
      - /app/config/overrides.integration.generated.yaml
    stop_grace_period: 30000ms
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
    ports:
      - "9091:9091"
      - "9201:9201"
      - "2345:2345"