// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include <memory>
#include <functional>
#include <optional>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <variant>

#include <boost/asio/any_io_executor.hpp>
#include <boost/asio/awaitable.hpp>
#include <agrpc/grpc_context.hpp>


#include "orderservice/config/config.generated.hpp"
#include "orderservice/internal/serdes/serde_registration.generated.hpp"
#include <servicelib/runtime/config/config.hpp>
#include <servicelib/runtime/serviceapp.hpp>
#include <servicelib/transformation/streams.hpp>
#include <servicelib/datasink/grpc/asio.hpp>
#include <servicelib/runtime/detail/grpc_client.hpp>
#include <servicelib/datasource/http/beast.hpp>
#include <servicelib/datasink/kafka/librdkafka.hpp>

#include <handlers/order_service_api/processorder/requests.hpp>
#include <handlers/order_service_api/processorder/responses.hpp>
#include <model_cpp/include/example/model/types/order_item.hpp>
#include <model_cpp/include/example/model/types/order_item_result.hpp>
#include <model_cpp/include/example/model/types/order_processed.hpp>
#include <orderservice/internal/functions/endpoint/order_processed_endpoint_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_item_sink.hpp>
#include <orderservice/internal/functions/endpoint/process_order_source.hpp>
#include <orderservice/internal/functions/order/map_order_item_result_to_order_state.hpp>
#include <orderservice/internal/functions/order/map_to_order_processed.hpp>
#include <orderservice/internal/functions/order/map_to_order_state.hpp>
#include <orderservice/internal/functions/order/process_order_items.hpp>
#include <orderservice/internal/functions/order/soft_deadline.hpp>
#include <orderservice/internal/types/order.hpp>
#include <orderservice/internal/types/order_state.hpp>
#include <proto/inventoryserviceapi/inventoryserviceapi.generated.grpc.pb.h>
#include <proto/inventoryserviceapi/processorderitem/processorderitem.pb.h>


namespace example::order_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,
                   agrpc::GrpcContext& grpc_context,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;

 protected:
  struct ServiceMakers final {
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::MapOrderItemResultToOrderState>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_order_item_result_to_order_state;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::MapToOrderProcessed>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_to_order_processed;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::MapToOrderState>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::MapStreamConfig&)> map_to_order_state;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::OrderProcessedEndpointSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::KafkaEndpointConfig&)> order_processed_endpoint_sink;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::ProcessOrderItemSink>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcEndpointConfig&)> process_order_item_sink;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::ProcessOrderItems>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::FlatMapStreamConfig&)> process_order_items;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::ProcessOrderSource>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::HttpEndpointConfig&)> process_order_source;
    std::function<boost::asio::awaitable<
        std::unique_ptr<functions::SoftDeadline>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::DelayStreamConfig&)> soft_deadline;
    std::function<boost::asio::awaitable<
        std::shared_ptr<servicelib::http::Router>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&)> http_router;
    std::function<boost::asio::awaitable<
        std::unique_ptr<servicelib::http::Server>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::ServiceConfig&,
        std::shared_ptr<servicelib::http::Router>)> http_server;

    std::function<boost::asio::awaitable<std::unique_ptr<
        servicelib::grpc_transport::ClientPool<inventoryserviceapi::InventoryServiceApi::Stub>>>(
        servicelib::Context, servicelib::IServiceEnvironment&,
        const servicelib::config::GrpcDataConnectorConfig&)> inventory_service_api_client;
  };
  struct ServiceFunctions final {
    std::unique_ptr<functions::MapOrderItemResultToOrderState> map_order_item_result_to_order_state;
    std::unique_ptr<functions::MapToOrderProcessed> map_to_order_processed;
    std::unique_ptr<functions::MapToOrderState> map_to_order_state;
    std::unique_ptr<functions::OrderProcessedEndpointSink> order_processed_endpoint_sink;
    std::unique_ptr<functions::ProcessOrderItemSink> process_order_item_sink;
    std::unique_ptr<functions::ProcessOrderItems> process_order_items;
    std::unique_ptr<functions::ProcessOrderSource> process_order_source;
    std::unique_ptr<functions::SoftDeadline> soft_deadline;
  };

  ServiceMakers makers_;
  ServiceFunctions functions_;

  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  void initMakers();
  void initInfrastructure(servicelib::Context context,
                          const config::Config& config,
                          const servicelib::config::ServiceConfig& service_config);
  void initFunctions(servicelib::Context context, const config::Config& config);
  void initRuntime(servicelib::Context context);
  void initStreams(const config::Config& config);
  void initDataSinks(const config::Config& config);
  void initDataSources(const config::Config& config);
  void stopRuntime() noexcept;
  void releaseRuntime() noexcept;

  using ProcessOrderInput =
      servicelib::InputStream<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
                              ServiceGenerated>;


  struct ServiceStreams final {
    ProcessOrderInput* process_order{};
    servicelib::StreamBase* split_pipeline{nullptr};

    servicelib::StreamBase* process_order_items{nullptr};

    servicelib::SinkEndpointStreamRef<example::model::types::OrderItem, example::model::types::OrderItemResult, example::order_service::types::OrderState> process_order_item;

    servicelib::StreamBase* map_order_item_result_to_order_state{nullptr};

    servicelib::StreamBase* soft_deadline{nullptr};

    servicelib::StreamBase* map_to_order_state{nullptr};

    servicelib::StreamBase* merge_results{nullptr};

    servicelib::StreamBase* split_order_result{nullptr};

    servicelib::StreamBase* map_to_order_processed{nullptr};

    servicelib::SinkEndpointStreamRef<example::model::types::OrderProcessed, std::monostate, std::exception_ptr> publish_order_processed;

  };
  ServiceStreams streams_;

  struct ProcessOrderItemSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderItem&)>
        consume;
    struct Function final {
      ProcessOrderItemSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderItem& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };
  struct PublishOrderProcessedSinkBinding final {
    std::function<void(servicelib::MessageContext, const example::model::types::OrderProcessed&)>
        consume;
    struct Function final {
      PublishOrderProcessedSinkBinding* binding;
      void operator()(servicelib::MessageContext context,
                      const example::model::types::OrderProcessed& value) const {
        if (!binding->consume) {
          throw std::logic_error("sink endpoint is not bound");
        }
        binding->consume(std::move(context), value);
      }
    };
  };

  struct ServiceBindings final {
    ProcessOrderItemSinkBinding process_order_item;
    PublishOrderProcessedSinkBinding publish_order_processed;
  };
  ServiceBindings bindings_;



  struct ProcessOrderItemGrpcClientFunction final {
    servicelib::grpc_transport::ClientPool<inventoryserviceapi::InventoryServiceApi::Stub>* client;
    void async(
        processorderitem::ProcessOrderItemRequest request,
        servicelib::datasink::grpc::CallOptions options,
        std::function<void(std::exception_ptr,
                           std::optional<processorderitem::ProcessOrderItemResponse>)> completion) const {
      client->template asyncUnary<
          &inventoryserviceapi::InventoryServiceApi::Stub::PrepareAsyncProcessOrderItem, processorderitem::ProcessOrderItemRequest,
          processorderitem::ProcessOrderItemResponse>(std::move(request), std::move(options),
                             std::move(completion));
    }
  };
  using ProcessOrderItemGrpcSinkEndpoint =
      servicelib::datasink::grpc::NoStreamingEndpoint<
          processorderitem::ProcessOrderItemRequest, processorderitem::ProcessOrderItemResponse, example::model::types::OrderItem, example::model::types::OrderItemResult,
          functions::ProcessOrderItemSink, ProcessOrderItemGrpcClientFunction, example::order_service::types::OrderState>;

  using ProcessOrderHTTPSourceConsumer =
      servicelib::datasource::http::BeastEndpointConsumer<
          example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr,
          ServiceGenerated, functions::ProcessOrderSource>;

 public:
  std::shared_ptr<servicelib::datasource::http::IBeastEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;
 private:



  using PublishOrderProcessedKafkaSinkEndpoint =
      servicelib::datasink::kafka::Endpoint<
          example::model::types::OrderProcessed, std::monostate, functions::OrderProcessedEndpointSink, std::exception_ptr>;




  struct ServiceEndpoints final {
    std::shared_ptr<ProcessOrderItemGrpcSinkEndpoint> process_order_item;
    std::shared_ptr<ProcessOrderHTTPSourceConsumer> process_order;
    std::shared_ptr<PublishOrderProcessedKafkaSinkEndpoint> publish_order_processed;
  };
  ServiceEndpoints endpoints_;

  struct ServiceConnectors final {
    std::unique_ptr<
        servicelib::grpc_transport::ClientPool<inventoryserviceapi::InventoryServiceApi::Stub>> inventory_service_api_client;
    std::shared_ptr<
        servicelib::datasink::grpc::DataSink> inventory_service_api_sink;
    std::shared_ptr<
        servicelib::datasource::http::BeastDataSource> order_service_api_source;

    std::unique_ptr<
        servicelib::datasink::kafka::LibrdkafkaProducerClient> publish_order_processed_producer;
  };
  ServiceConnectors connectors_;

  std::shared_ptr<servicelib::http::Router> http_router_;
  std::unique_ptr<servicelib::http::Server> http_server_;

  boost::asio::any_io_executor executor_;
  agrpc::GrpcContext* grpc_context_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
};

}  // namespace example::order_service::app