// Code generated by servicegen. DO NOT EDIT.
#include "orderservice/internal/app/service.generated.hpp"

#include <algorithm>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/use_future.hpp>
#include <chrono>
#include <cstdint>
#include <exception>
#include <future>
#include <mutex>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <servicelib/runtime/environment/metrics/prometheus.hpp>
#include <servicelib/runtime/status/http.hpp>

#include "orderservice/internal/app/service.hpp"

namespace example::order_service::app {

ServiceGenerated::ServiceGenerated(
    boost::asio::any_io_executor executor,
    agrpc::GrpcContext& grpc_context,

    std::shared_ptr<const config::Config> config,
    servicelib::log::Logger& logger,
    servicelib::metrics::Metrics& metrics,
    servicelib::tracing::Tracing* tracing)
    : executor_(std::move(executor)),
      grpc_context_(&grpc_context),

      config_(std::move(config)),
      logger_(&logger),
      metrics_(&metrics),
      tracing_(tracing) {
  if (!executor_) {
    throw std::invalid_argument("service Asio executor is not initialized");
  }
  if (!config_) {
    throw std::invalid_argument("service config is null");
  }
  runtime_config_ =
      servicelib::config::detail::MakeRuntimeConfigSnapshot(config_);
}

ServiceGenerated::~ServiceGenerated() {
  stopRuntime();
  releaseRuntime();
}

void ServiceGenerated::start() {
  try {
    const servicelib::Context context;
    servicelib::config::RuntimeConfigRegistry::Publish(runtime_config_);
    serviceInit();
    initMakers();
    customMakersInit(context);
    initRuntime(context);
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::start();
    lifecycle_started_ = true;
    http_server_->Start();
    serviceStarted();
  } catch (...) {
    stop();
    throw;
  }
}

void ServiceGenerated::initMakers() {
  makers_.map_order_item_result_to_order_state = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::MapOrderItemResultToOrderState>> {
    return functions::MakeMapOrderItemResultToOrderState(
        std::move(context), environment, config);
  };
  makers_.map_to_order_processed = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::MapToOrderProcessed>> {
    return functions::MakeMapToOrderProcessed(
        std::move(context), environment, config);
  };
  makers_.map_to_order_state = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::MapStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::MapToOrderState>> {
    return functions::MakeMapToOrderState(
        std::move(context), environment, config);
  };
  makers_.order_processed_endpoint_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::KafkaEndpointConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::OrderProcessedEndpointSink>> {
    return functions::MakeOrderProcessedEndpointSink(
        std::move(context), environment, config);
  };
  makers_.process_order_item_sink = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcEndpointConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::ProcessOrderItemSink>> {
    return functions::MakeProcessOrderItemSink(
        std::move(context), environment, config);
  };
  makers_.process_order_items = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::FlatMapStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::ProcessOrderItems>> {
    return functions::MakeProcessOrderItems(
        std::move(context), environment, config);
  };
  makers_.process_order_source = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::HttpEndpointConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::ProcessOrderSource>> {
    return functions::MakeProcessOrderSource(
        std::move(context), environment, config);
  };
  makers_.soft_deadline = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::DelayStreamConfig& config) -> boost::asio::awaitable<
          std::unique_ptr<functions::SoftDeadline>> {
    return functions::MakeSoftDeadline(
        std::move(context), environment, config);
  };
  makers_.http_router = [](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config)
      -> boost::asio::awaitable<std::shared_ptr<servicelib::http::Router>> {
    (void)context;
    (void)environment;
    (void)config;
    co_return std::make_shared<servicelib::http::Router>();
  };
  makers_.http_server = [this](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::ServiceConfig& config,
      std::shared_ptr<servicelib::http::Router> router)
      -> boost::asio::awaitable<std::unique_ptr<servicelib::http::Server>> {
    (void)context;
    (void)environment;
    if (config.httpPort < 0 || config.httpPort > 65535) {
      throw std::invalid_argument("service HTTP port is out of range");
    }
    servicelib::http::Server::Options options;
    options.address = config.httpHost.empty() ? std::string{"0.0.0.0"}
                                               : config.httpHost;
    options.port = static_cast<std::uint16_t>(config.httpPort);
    options.shutdownTimeout =
        std::chrono::milliseconds{std::max(config.shutdownTimeout, 0)};
    co_return std::make_unique<servicelib::http::Server>(
        executor_, std::move(router), std::move(options));
  };

  makers_.inventory_service_api_client = [this](
      servicelib::Context context, servicelib::IServiceEnvironment& environment,
      const servicelib::config::GrpcDataConnectorConfig& config)
      -> boost::asio::awaitable<std::unique_ptr<
          servicelib::grpc_transport::ClientPool<inventoryserviceapi::InventoryServiceApi::Stub>>> {
    (void)context;
    (void)environment;
    if (config.connectionsCount < 1) {
      throw std::invalid_argument(
          "gRPC connector " + config.name +
          " connectionsCount must be at least 1");
    }
    co_return std::make_unique<
        servicelib::grpc_transport::ClientPool<inventoryserviceapi::InventoryServiceApi::Stub>>(
        *grpc_context_, config.address,
        static_cast<std::size_t>(config.connectionsCount),
        [] (std::shared_ptr<::grpc::Channel> channel) {
          return inventoryserviceapi::InventoryServiceApi::NewStub(std::move(channel));
        });
  };
}

void ServiceGenerated::initInfrastructure(
    servicelib::Context context, const config::Config& cfg,
    const servicelib::config::ServiceConfig& service_config) {
  if (!makers_.http_router || !makers_.http_server) {
    throw std::logic_error("HTTP infrastructure makers are not configured");
  }

  http_router_ = boost::asio::co_spawn(
      executor_, makers_.http_router(context, *this, service_config),
      boost::asio::use_future).get();
  if (!http_router_) {
    throw std::logic_error("HTTP router maker returned null");
  }
  std::stop_source maker_cancellation;
  std::mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<std::future<void>> maker_tasks;
  const auto launch = [&](auto task) {
    maker_tasks.push_back(boost::asio::co_spawn(
        executor_, std::move(task), boost::asio::use_future));
  };
  launch([](ServiceGenerated* service,
            servicelib::config::ServiceConfig service_config,
            servicelib::Context maker_context,
            std::stop_source* maker_cancellation,
            std::mutex* maker_error_mutex,
            std::exception_ptr* first_maker_error)
             -> boost::asio::awaitable<void> {
    try {
      service->http_server_ = co_await service->makers_.http_server(
          maker_context, *service, service_config, service->http_router_);
      if (!service->http_server_) {
        throw std::logic_error("HTTP server maker returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
  }(this, service_config, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error));

  if (!makers_.inventory_service_api_client) {
    throw std::logic_error("infrastructure maker inventory_service_api_client is not configured");
  }
  launch([](ServiceGenerated* service,
            servicelib::config::GrpcDataConnectorConfig connector_config,
            servicelib::Context maker_context,
            std::stop_source* maker_cancellation,
            std::mutex* maker_error_mutex,
            std::exception_ptr* first_maker_error)
             -> boost::asio::awaitable<void> {
    try {
      service->connectors_.inventory_service_api_client = co_await service->makers_.inventory_service_api_client(
          maker_context, *service, connector_config);
      if (!service->connectors_.inventory_service_api_client) {
        throw std::logic_error("infrastructure maker inventory_service_api_client returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
  }(this, cfg.dataConnectors.inventoryServiceApi, maker_context,
    &maker_cancellation, &maker_error_mutex, &first_maker_error));
  for (auto& task : maker_tasks) {
    try {
      task.get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initFunctions(
    servicelib::Context context, const config::Config& cfg) {
  if (!makers_.map_order_item_result_to_order_state) {
    throw std::logic_error("function maker MapOrderItemResultToOrderState is not configured");
  }
  if (!makers_.map_to_order_processed) {
    throw std::logic_error("function maker MapToOrderProcessed is not configured");
  }
  if (!makers_.map_to_order_state) {
    throw std::logic_error("function maker MapToOrderState is not configured");
  }
  if (!makers_.order_processed_endpoint_sink) {
    throw std::logic_error("function maker OrderProcessedEndpointSink is not configured");
  }
  if (!makers_.process_order_item_sink) {
    throw std::logic_error("function maker ProcessOrderItemSink is not configured");
  }
  if (!makers_.process_order_items) {
    throw std::logic_error("function maker ProcessOrderItems is not configured");
  }
  if (!makers_.process_order_source) {
    throw std::logic_error("function maker ProcessOrderSource is not configured");
  }
  if (!makers_.soft_deadline) {
    throw std::logic_error("function maker SoftDeadline is not configured");
  }
  std::stop_source maker_cancellation;
  std::mutex maker_error_mutex;
  std::exception_ptr first_maker_error;
  const auto maker_context = context.withExternalCancellation(
      maker_cancellation.get_token());
  std::vector<std::future<void>> maker_tasks;
  maker_tasks.reserve(8);
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::MapStreamConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.map_order_item_result_to_order_state = co_await service->makers_.map_order_item_result_to_order_state(
          maker_context, *service, function_config);
      if (!service->functions_.map_order_item_result_to_order_state) {
        throw std::logic_error("function maker MapOrderItemResultToOrderState returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.streams.mapOrderItemResultToOrderState, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::MapStreamConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.map_to_order_processed = co_await service->makers_.map_to_order_processed(
          maker_context, *service, function_config);
      if (!service->functions_.map_to_order_processed) {
        throw std::logic_error("function maker MapToOrderProcessed returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.streams.mapToOrderProcessed, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::MapStreamConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.map_to_order_state = co_await service->makers_.map_to_order_state(
          maker_context, *service, function_config);
      if (!service->functions_.map_to_order_state) {
        throw std::logic_error("function maker MapToOrderState returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.streams.mapToOrderState, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::KafkaEndpointConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.order_processed_endpoint_sink = co_await service->makers_.order_processed_endpoint_sink(
          maker_context, *service, function_config);
      if (!service->functions_.order_processed_endpoint_sink) {
        throw std::logic_error("function maker OrderProcessedEndpointSink returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.endpoints.orderProcessed, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::GrpcEndpointConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.process_order_item_sink = co_await service->makers_.process_order_item_sink(
          maker_context, *service, function_config);
      if (!service->functions_.process_order_item_sink) {
        throw std::logic_error("function maker ProcessOrderItemSink returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.endpoints.processOrderItem, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::FlatMapStreamConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.process_order_items = co_await service->makers_.process_order_items(
          maker_context, *service, function_config);
      if (!service->functions_.process_order_items) {
        throw std::logic_error("function maker ProcessOrderItems returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.streams.processOrderItems, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::HttpEndpointConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.process_order_source = co_await service->makers_.process_order_source(
          maker_context, *service, function_config);
      if (!service->functions_.process_order_source) {
        throw std::logic_error("function maker ProcessOrderSource returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.endpoints.processOrder, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));
  maker_tasks.push_back(boost::asio::co_spawn(
      executor_,
      [](ServiceGenerated* service, servicelib::config::DelayStreamConfig function_config,
         servicelib::Context maker_context,
         std::stop_source* maker_cancellation,
         std::mutex* maker_error_mutex,
         std::exception_ptr* first_maker_error)
          -> boost::asio::awaitable<void> {
    try {
      service->functions_.soft_deadline = co_await service->makers_.soft_deadline(
          maker_context, *service, function_config);
      if (!service->functions_.soft_deadline) {
        throw std::logic_error("function maker SoftDeadline returned null");
      }
    } catch (...) {
      maker_cancellation->request_stop();
      const std::lock_guard lock(*maker_error_mutex);
      if (!*first_maker_error) {
        *first_maker_error = std::current_exception();
      }
      throw;
    }
    co_return;
  }(this, cfg.streams.softDeadline, maker_context, &maker_cancellation,
    &maker_error_mutex, &first_maker_error), boost::asio::use_future));

  for (auto& task : maker_tasks) {
    try {
      task.get();
    } catch (...) {
      // The task recorded the first failure before requesting cancellation.
    }
  }
  maker_cancellation.request_stop();
  if (first_maker_error) std::rethrow_exception(first_maker_error);
}

void ServiceGenerated::initRuntime(servicelib::Context context) {
  const auto runtime_config = getRuntimeConfigSnapshot();
  if (!runtime_config) {
    throw std::runtime_error("servicelib runtime config is not published");
  }
  const auto config_snapshot = std::dynamic_pointer_cast<const config::Config>(
      std::shared_ptr<const servicelib::config::IConfig>(
          runtime_config, &runtime_config->GetConfig()));
  if (!config_snapshot) {
    throw std::runtime_error("servicelib runtime config has unexpected type");
  }
  this->ensureConfiguredPools();
  const auto service_config = getServiceConfigSnapshot();
  if (!service_config) {
    throw std::runtime_error("service config is null");
  }
  initInfrastructure(context, *config_snapshot, *service_config);
  initFunctions(context, *config_snapshot);
  customFunctionsInit(context);
  initStreams(*config_snapshot);
  initDataSinks(*config_snapshot);

  initDataSources(*config_snapshot);
  servicelib::http::RegisterStatusRoutes(
      *http_router_, *this, [this] {
        if (const auto* prometheus =
                dynamic_cast<const servicelib::metrics::PrometheusMetrics*>(
                    metrics_)) {
          return prometheus->Expose();
        }
        return std::string{};
      }, service_config->statusHandler, service_config->metricsHandler,
      service_config->startupHandler, service_config->readinessHandler,
      service_config->livenessHandler);
}

void ServiceGenerated::initStreams(const config::Config& cfg) {
  streams_.process_order = &servicelib::makeInputStreamRef<example::order_service::types::Order, example::order_service::types::OrderState, std::exception_ptr, ServiceGenerated>(cfg.streams.processOrder, nullptr, *this);
  auto& split_pipeline = (*streams_.process_order).template split<2>(cfg.streams.splitPipeline);
  streams_.split_pipeline = std::addressof(split_pipeline);
  auto& process_order_items = split_pipeline.template get<0>().flatMap(cfg.streams.processOrderItems, servicelib::StreamType<example::model::types::OrderItem>{}, servicelib::StreamFunction(std::ref(*functions_.process_order_items)));
  streams_.process_order_items = std::addressof(process_order_items);
  auto& process_order_item = process_order_items.sinkWithResult(cfg.streams.processOrderItem, servicelib::StreamType<example::model::types::OrderItemResult>{}, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(ProcessOrderItemSinkBinding::Function{&bindings_.process_order_item}));
  streams_.process_order_item = process_order_item;
  auto& map_order_item_result_to_order_state = process_order_item.map(cfg.streams.mapOrderItemResultToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_order_item_result_to_order_state)));
  streams_.map_order_item_result_to_order_state = std::addressof(map_order_item_result_to_order_state);
  auto& soft_deadline = split_pipeline.template get<1>().delay(cfg.streams.softDeadline, servicelib::StreamFunction(std::ref(*functions_.soft_deadline)));
  streams_.soft_deadline = std::addressof(soft_deadline);
  auto& map_to_order_state = soft_deadline.map(cfg.streams.mapToOrderState, servicelib::StreamType<example::order_service::types::OrderState>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_state)));
  streams_.map_to_order_state = std::addressof(map_to_order_state);
  auto& merge_results = map_to_order_state.merge(cfg.streams.mergeResults, map_order_item_result_to_order_state, process_order_item.getErrorStream());
  streams_.merge_results = std::addressof(merge_results);
  auto& split_order_result = merge_results.template split<2>(cfg.streams.splitOrderResult);
  streams_.split_order_result = std::addressof(split_order_result);
  auto& map_to_order_processed = split_order_result.template get<0>().map(cfg.streams.mapToOrderProcessed, servicelib::StreamType<example::model::types::OrderProcessed>{}, servicelib::StreamFunction(std::ref(*functions_.map_to_order_processed)));
  streams_.map_to_order_processed = std::addressof(map_to_order_processed);
  [[maybe_unused]] auto& publish_order_processed = map_to_order_processed.sink(cfg.streams.publishOrderProcessed, servicelib::StreamType<std::exception_ptr>{}, servicelib::StreamFunction(PublishOrderProcessedSinkBinding::Function{&bindings_.publish_order_processed}));
  streams_.publish_order_processed = publish_order_processed;
  streams_.process_order->setSource(split_order_result.template get<1>());
}

void ServiceGenerated::initDataSinks(const config::Config& cfg) {
  (void)cfg;
  {
  }
  connectors_.inventory_service_api_sink =
      servicelib::datasink::grpc::DataSink::make(
          streams_.process_order_item.get());
  endpoints_.process_order_item = std::make_shared<ProcessOrderItemGrpcSinkEndpoint>(
      streams_.process_order_item.get(),
      *functions_.process_order_item_sink,
      ProcessOrderItemGrpcClientFunction{&*connectors_.inventory_service_api_client});
  bindings_.process_order_item.consume =
      [endpoint = endpoints_.process_order_item.get()](
          servicelib::MessageContext context, const example::model::types::OrderItem& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderItem>::make(value));
      };
  connectors_.inventory_service_api_sink->addEndpoint(endpoints_.process_order_item);
  registerDataSink(connectors_.inventory_service_api_sink);


  connectors_.publish_order_processed_producer =
      std::make_unique<servicelib::datasink::kafka::LibrdkafkaProducerClient>(
          getMetrics());
  endpoints_.publish_order_processed = std::make_shared<PublishOrderProcessedKafkaSinkEndpoint>(
      streams_.publish_order_processed.get(), *connectors_.publish_order_processed_producer,
      *functions_.order_processed_endpoint_sink);
  bindings_.publish_order_processed.consume =
      [endpoint = endpoints_.publish_order_processed.get()](
          servicelib::MessageContext context, const example::model::types::OrderProcessed& value) {
        endpoint->consume(std::move(context),
                          servicelib::Payload<example::model::types::OrderProcessed>::make(value));
      };
  registerDataSink(endpoints_.publish_order_processed);

}

void ServiceGenerated::initDataSources(
    const config::Config& cfg) {
  (void)cfg;

  connectors_.order_service_api_source =
      servicelib::datasource::http::BeastDataSource::make(
          *this, *streams_.process_order);
  endpoints_.process_order = ProcessOrderHTTPSourceConsumer::make(
      *this, *streams_.process_order,
      *functions_.process_order_source);
  connectors_.order_service_api_source->addEndpoint(endpoints_.process_order->endpoint());
  connectors_.order_service_api_source->registerRoutes(*http_router_);
  registerDataSource(connectors_.order_service_api_source);



}


void ServiceGenerated::stop() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  try {
    if (lifecycle_started_) {
      lifecycle_started_ = false;
      serviceStopping();
    }
  } catch (const std::exception& ex) {
    report_failure("serviceStopping", ex.what());
  } catch (...) {
    report_failure("serviceStopping", "unknown exception");
  }

  stopRuntime();
}

void ServiceGenerated::stopRuntime() noexcept {
  const auto report_failure =
      [this](std::string_view operation, std::string_view error) noexcept {
        try {
          getLogger().error(
              "generated service shutdown failed",
              {servicelib::log::Field::Str("operation", std::string(operation)),
               servicelib::log::Field::Err(error)});
        } catch (...) {
          // Logging must not escape a noexcept service destructor.
        }
      };

  if (http_server_) http_server_->Stop();


  try {
    servicelib::ServiceApp<ServiceGenerated, DataTypes>::stop();
  } catch (const std::exception& ex) {
    report_failure("ServiceApp::stop", ex.what());
  } catch (...) {
    report_failure("ServiceApp::stop", "unknown exception");
  }
}

void ServiceGenerated::releaseRuntime() noexcept {
  // ServiceApp::stop() has already stopped and released the runtime-owned
  // graph. Generated fields are only typed construction/runtime views.
  connectors_ = {};
  endpoints_ = {};
  bindings_ = {};
  streams_ = {};
  functions_ = {};
  http_server_.reset();
  http_router_.reset();
  servicelib::config::RuntimeConfigRegistry::Publish({});
}

std::shared_ptr<
    servicelib::datasource::http::IBeastEndpoint>
ServiceGenerated::httpDataSourceEndpoint(int endpoint_id) const {
  if (auto endpoint = connectors_.order_service_api_source
          ? connectors_.order_service_api_source->endpoint(endpoint_id) : nullptr) {
    return endpoint;
  }
  throw std::invalid_argument(
      "HTTP datasource endpoint not found: " + std::to_string(endpoint_id));
}



servicelib::log::Logger& ServiceGenerated::getLogger() {
  return *logger_;
}

servicelib::metrics::Metrics& ServiceGenerated::getMetrics() {
  return *metrics_;
}

servicelib::tracing::Tracing* ServiceGenerated::getTracing() {
  return tracing_;
}

}  // namespace example::order_service::app