// Code generated by servicegen. DO NOT EDIT.
#pragma once

#include "orderservice/internal/app/makers.generated.hpp"
#include "orderservice/internal/app/functions.generated.hpp"
#include "orderservice/internal/app/streams.generated.hpp"
#include "orderservice/internal/app/bindings.generated.hpp"
#include "orderservice/internal/app/endpoints.generated.hpp"
#include "orderservice/internal/app/connectors.generated.hpp"
#include "orderservice/internal/app/clients.generated.hpp"
#include "orderservice/internal/app/servers.generated.hpp"
#include "orderservice/internal/app/substreams.generated.hpp"

namespace example::order_service::app {

struct DataTypes final {
  template <typename>
  struct DataType {};
};

class ServiceGenerated
    : public servicelib::ServiceApp<ServiceGenerated, DataTypes> {
 public:
  ServiceGenerated(boost::asio::any_io_executor executor,
                   agrpc::GrpcContext& grpc_context,

                   std::shared_ptr<const config::Config> config,
                   servicelib::log::Logger& logger,
                   servicelib::metrics::Metrics& metrics,
                   servicelib::tracing::Tracing* tracing = nullptr);
  ~ServiceGenerated() override;

  void start();
  void stop() noexcept;

  servicelib::log::Logger& getLogger() override;
  servicelib::metrics::Metrics& getMetrics() override;
  servicelib::tracing::Tracing* getTracing() override;




  std::shared_ptr<servicelib::datasource::http::IBeastEndpoint>
  httpDataSourceEndpoint(int endpoint_id) const;

 protected:
  using ServiceMakers = example::order_service::app::ServiceMakers;
  using ServiceFunctions = example::order_service::app::ServiceFunctions;
  ServiceMakers makers_;
  ServiceFunctions functions_;
  virtual void customMakersInit(servicelib::Context) {}
  virtual void customFunctionsInit(servicelib::Context) {}
  virtual void serviceInit() {}
  virtual void serviceStarted() {}
  virtual void serviceStopping() noexcept {}

 private:
  friend struct ServiceServers;
  friend struct ServiceEndpoints;
  void initRuntime(servicelib::Context context);
  void stopRuntime() noexcept;
  void releaseRuntime() noexcept;
  ServiceStreams streams_;
  ServiceBindings bindings_;
  ServiceEndpoints endpoints_;
  ServiceConnectors connectors_;
  ServiceClients clients_;
  ServiceServers servers_;
  ServiceSubStreams substreams_;

  boost::asio::any_io_executor executor_;
  agrpc::GrpcContext* grpc_context_;

  std::shared_ptr<const config::Config> config_;
  std::shared_ptr<const servicelib::config::RuntimeConfig> runtime_config_;
  servicelib::log::Logger* logger_;
  servicelib::metrics::Metrics* metrics_;
  servicelib::tracing::Tracing* tracing_;
  bool lifecycle_started_{false};
};


}  // namespace example::order_service::app